import { defineArrayMember, defineField, defineType } from "sanity";

const categories = [
  { title: "Residential", value: "Residential" },
  { title: "Hospitality", value: "Hospitality" },
  { title: "Architecture", value: "Architecture" },
  { title: "Interior", value: "Interior" },
  { title: "Commercial", value: "Commercial" },
  { title: "Concept", value: "Concept" },
];

const serviceSuggestions = [
  "Architecture",
  "Interior design",
  "Spatial planning",
  "Material concept",
  "Lighting concept",
  "Visualization",
  "Custom furniture",
  "Hospitality concept",
  "Exterior concept",
  "Children's room concept",
  "Small-space planning",
  "Joinery concept",
];

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "overview", title: "Overview", default: true },
    { name: "details", title: "Details" },
    { name: "images", title: "Images" },
    { name: "publishing", title: "Publishing" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Project title",
      type: "localizedString",
      description: "The public project name shown on the Work page and detail page.",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "URL slug",
      type: "slug",
      description: "Click Generate after adding the title. Keep this short and readable.",
      group: "overview",
      options: { source: "title.sv", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Short intro",
      type: "localizedText",
      description: "One or two sentences used on project cards and preview panels.",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Full project story",
      type: "localizedBlockContent",
      description: "The main text for the project detail page. Use short paragraphs.",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      description: "Example: 2024",
      group: "details",
      validation: (rule) => rule.required().regex(/^\d{4}$/, "Use a four-digit year."),
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "localizedString",
      description: "Example: Skopje, N. Macedonia",
      group: "details",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      description: "Used for filtering on the Work page.",
      group: "details",
      options: {
        list: categories,
        layout: "radio",
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "siteSize",
      title: "Area",
      type: "string",
      description: "Example: 54 m². Leave empty if not relevant.",
      group: "details",
    }),
    defineField({
      name: "services",
      title: "Services",
      type: "array",
      description: "Add the services Lagom provided for this project.",
      group: "details",
      of: [
        defineArrayMember({
          type: "string",
          options: { list: serviceSuggestions },
        }),
      ],
      options: { layout: "tags" },
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: "featuredImage",
      title: "Main project image",
      type: "projectImage",
      description: "Large hero image. Upload the original render/photo; do not compress it first.",
      group: "images",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "thumbnailImage",
      title: "Optional thumbnail image",
      type: "projectImage",
      description: "Optional alternate crop for cards. If empty, the main project image is used.",
      group: "images",
    }),
    defineField({
      name: "gallery",
      title: "Project gallery",
      type: "array",
      description: "Add images in the order they should appear. Originals are fine.",
      group: "images",
      of: [defineArrayMember({ type: "projectImage" })],
      validation: (rule) => rule.min(1).warning("Add at least one gallery image when possible."),
    }),
    defineField({
      name: "workGallery",
      title: "Atlas view images",
      type: "array",
      description: "Optional. Select up to five priority images for the draggable Atlas view. Reuse original assets; the website creates optimized AVIF/WebP variants automatically. Any remaining positions are filled from the main image and project gallery.",
      group: "images",
      of: [defineArrayMember({ type: "projectImage" })],
      validation: (rule) => rule.max(5).warning("The Atlas view displays no more than five images per project."),
    }),
    defineField({
      name: "credits",
      title: "Credits / notes",
      type: "localizedBlockContent",
      description: "Optional notes such as collaborators, photographer, or project scale.",
      group: "details",
    }),
    defineField({
      name: "orderRank",
      title: "Display order",
      type: "number",
      description: "Lower numbers appear first. Example: 10, 20, 30.",
      group: "publishing",
      initialValue: 100,
      validation: (rule) => rule.required().integer().min(0),
    }),
    defineField({
      name: "isPublished",
      title: "Published on website",
      type: "boolean",
      description: "Turn this off to keep a draft project inside the CMS.",
      group: "publishing",
      initialValue: true,
    }),
    defineField({
      name: "seoTitle",
      title: "SEO title",
      type: "localizedString",
      description: "Optional. If empty, the project title is used.",
      group: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO description",
      type: "localizedText",
      description: "Optional search/social description.",
      group: "seo",
    }),
  ],
  initialValue: {
    category: "Residential",
    isPublished: true,
    orderRank: 100,
  },
  orderings: [
    {
      title: "Display order",
      name: "displayOrder",
      by: [{ field: "orderRank", direction: "asc" }],
    },
    {
      title: "Year, newest first",
      name: "yearDesc",
      by: [{ field: "year", direction: "desc" }],
    },
    {
      title: "Title A-Z",
      name: "titleAsc",
      by: [{ field: "title.sv", direction: "asc" }],
    },
  ],
  preview: {
    select: {
      title: "title.sv",
      year: "year",
      location: "location.sv",
      isPublished: "isPublished",
      media: "featuredImage",
    },
    prepare: ({ title, year, location, isPublished, media }) => ({
      title: title || "Untitled project",
      subtitle: `${year || "No year"} · ${location || "No location"} · ${isPublished === false ? "Draft" : "Published"}`,
      media,
    }),
  },
});
